/**
 * Every project needs the same ~8 boilerplate files (package.json, Firebase
 * client init, README, etc). They used to be generated by an LLM coder call
 * each - identical content, paid for from scratch every single time, and a
 * source of drift (e.g. the coder inventing a different export name in
 * lib/firebase.js on one run than another).
 *
 * These are pure functions of the Plan - there is nothing for a model to
 * decide here - so they're templated in code instead. This eliminates
 * ~7-8 of the ~18-20 coder calls a Next.js+Firebase project used to need,
 * which is the majority of the token cost added when the pipeline moved
 * off static HTML/CSS/JS (see prompts.ts). It also makes lib/firebase.js
 * and firestore.rules provably correct instead of "probably correct."
 */

import type { Plan, FirestoreCollection, VirtualFS } from "./types";

function slugify(name: string): string {
  const slug = name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug || "generated-app";
}

const ENV_KEYS = [
  "NEXT_PUBLIC_FIREBASE_API_KEY",
  "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",
  "NEXT_PUBLIC_FIREBASE_PROJECT_ID",
  "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET",
  "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
  "NEXT_PUBLIC_FIREBASE_APP_ID",
] as const;

function packageJson(plan: Plan): string {
  const pkg = {
    name: slugify(plan.name),
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
    },
    dependencies: {
      next: "14.2.5",
      react: "^18.3.1",
      "react-dom": "^18.3.1",
      firebase: "^10.12.2",
      "lucide-react": "^0.400.0",
    },
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}

const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;
`;

const JSCONFIG = `{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    }
  },
  "exclude": ["node_modules"]
}
`;

const GITIGNORE = `# dependencies
/node_modules

# next.js
/.next/
/out/

# production
/build

# env
.env*.local

# misc
.DS_Store
*.pem
npm-debug.log*
`;

function envExample(): string {
  const lines = [
    "# Copy this file to .env.local and fill in the values from your Firebase project",
    "# (Firebase console -> Project settings -> General -> Your apps -> Web app -> SDK setup and configuration).",
    "",
    ...ENV_KEYS.map((k) => `${k}=`),
  ];
  return lines.join("\n") + "\n";
}

const FIREBASE_CLIENT_JS = `"use client";

import { initializeApp, getApps, getApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { getAuth } from "firebase/auth";

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

// Guard against re-initialization across Next.js hot reloads / multiple imports.
export const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
export const db = getFirestore(app);
export const auth = getAuth(app);
`;

function firestoreRules(collections: FirestoreCollection[]): string {
  if (collections.length === 0) {
    return `rules_version = '2';

service cloud.firestore {
  match /databases/{database}/documents {
    // This project doesn't persist any data yet - deny everything by default.
    match /{document=**} {
      allow read, write: if false;
    }
  }
}
`;
  }

  const collectionRules = collections
    .map((c) => {
      const create = c.publicCreate ? "if true" : "if false";
      return `    // ${c.purpose}
    match /${c.name}/{docId} {
      allow create: ${create};
      allow read, update, delete: if false; // only the owner, via Firebase console or Admin SDK
    }`;
    })
    .join("\n\n");

  return `rules_version = '2';

// Secure-by-default: visitors can only CREATE documents in the collections
// below (e.g. submitting a form); nobody can read, update, or delete from
// the client. Read your data via the Firebase console or a server-side
// Admin SDK you control.
service cloud.firestore {
  match /databases/{database}/documents {
${collectionRules}

    match /{document=**} {
      allow read, write: if false;
    }
  }
}
`;
}

function readme(plan: Plan, collections: FirestoreCollection[]): string {
  const collectionLines =
    collections.length > 0
      ? collections.map((c) => `- \`${c.name}\` - ${c.purpose}`).join("\n")
      : "- (none - this project doesn't persist any data)";

  const envLines = ENV_KEYS.map((k) => `${k}=...`).join("\n");

  return `# ${plan.name}

## What this is

${plan.description}

## 1. Install dependencies

\`\`\`
npm install
\`\`\`

## 2. Create a Firebase project

1. Go to https://console.firebase.google.com and create a new project.
2. Inside the project, click "Add app" -> Web (</>) to register a web app.
3. Enable **Firestore Database** (Build -> Firestore Database -> Create database -> Production mode).
4. Copy the \`firebaseConfig\` values shown after registering the web app - you'll need them in the next step.

## 3. Configure environment variables

Copy \`.env.local.example\` to \`.env.local\` and paste in the config values from step 2:

\`\`\`
${envLines}
\`\`\`

## 4. Apply Firestore security rules

This project ships with \`firestore.rules\` already written for its collections. Deploy them with the Firebase CLI:

\`\`\`
npm install -g firebase-tools
firebase login
firebase init firestore   # select your existing project, keep the existing firestore.rules when asked
firebase deploy --only firestore:rules
\`\`\`

**Firestore collections used by this app:**
${collectionLines}

## 5. Run locally

\`\`\`
npm run dev
\`\`\`

Open http://localhost:3000.

## 6. Push to GitHub

\`\`\`
git init
git add .
git commit -m "Initial commit"
\`\`\`

Create an empty repository on GitHub, then:

\`\`\`
git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git
git branch -M main
git push -u origin main
\`\`\`

## 7. Deploy

**Vercel (recommended, zero-config for Next.js):**

1. Go to https://vercel.com/new and import your GitHub repo.
2. Add the same environment variables from step 3 in the Vercel project settings (Settings -> Environment Variables).
3. Click Deploy.

CLI alternative:

\`\`\`
npm install -g vercel
vercel
\`\`\`

## Tech stack

- Next.js 14 (App Router)
- React 18
- Firebase (Firestore)
- Plain CSS
`;
}

/**
 * Generates every baseline file for a project deterministically from the
 * plan - no LLM call. Call this once, right after the planner returns, and
 * merge the result into the VirtualFS before the coder starts writing the
 * project-specific files (so lib/firebase.js etc. are already in context
 * for those coder calls - see coder.ts's selectContext()).
 */
export function generateBaselineFiles(plan: Plan): VirtualFS {
  const collections = plan.firestoreCollections ?? [];
  return {
    "package.json": packageJson(plan),
    "next.config.mjs": NEXT_CONFIG,
    "jsconfig.json": JSCONFIG,
    ".gitignore": GITIGNORE,
    ".env.local.example": envExample(),
    "lib/firebase.js": FIREBASE_CLIENT_JS,
    "firestore.rules": firestoreRules(collections),
    "README.md": readme(plan, collections),
  };
}

export const BASELINE_FILE_PATHS = [
  "package.json",
  "next.config.mjs",
  "jsconfig.json",
  ".gitignore",
  ".env.local.example",
  "lib/firebase.js",
  "firestore.rules",
  "README.md",
] as const;
